import { jsx as _jsx } from "react/jsx-runtime";
import { cn } from '@/lib/utils';
import React from 'react';
const H1 = React.forwardRef(({ className, ...props }, ref) => (_jsx("h1", { ref: ref, className: cn('scroll-m-20 text-4xl font-extrabold tracking-tight lg:text-5xl', className), ...props })));
H1.displayName = 'H1';
const H2 = React.forwardRef(({ className, ...props }, ref) => (_jsx("h2", { ref: ref, className: cn('scroll-m-20 border-b pb-2 text-3xl font-semibold tracking-tight first:mt-0', className), ...props })));
H2.displayName = 'H2';
const H3 = React.forwardRef(({ className, ...props }, ref) => (_jsx("h2", { ref: ref, className: cn('scroll-m-20 text-2xl font-semibold tracking-tight', className), ...props })));
H3.displayName = 'H3';
const H4 = React.forwardRef(({ className, ...props }, ref) => (_jsx("h4", { ref: ref, className: cn('scroll-m-20 text-xl font-semibold tracking-tight', className), ...props })));
H4.displayName = 'H4';
const P = React.forwardRef(({ className, ...props }, ref) => (_jsx("p", { ref: ref, className: cn('leading-7 [&:not(:first-child)]:mt-6', className), ...props })));
P.displayName = 'P';
const TextLarge = React.forwardRef(({ className, ...props }, ref) => (_jsx("div", { ref: ref, className: cn('text-lg font-semibold', className), ...props })));
TextLarge.displayName = 'TextLarge';
const TextMedium = React.forwardRef(({ className, ...props }, ref) => (_jsx("div", { ref: ref, className: cn('text-md font-semibold', className), ...props })));
TextMedium.displayName = 'TextMedium';
const TextSmall = React.forwardRef(({ className, ...props }, ref) => (_jsx("div", { ref: ref, className: cn('text-sm font-light leading-none', className), ...props })));
TextSmall.displayName = 'TextSmall';
export { H1, H2, H3, H4, P, TextLarge, TextMedium, TextSmall };
//# sourceMappingURL=typography.js.map